marksss=c(10 , 12, 13, 14 , 17)
marksss
mean(marksss)
x=sum(marks)
x
rel.freq=marksss/x
rel.freq
cum.freq=cumsum(marksss)
cum.freq
hist(marksss)
hist(x)
hist(rel.freq)
hist(cum.freq)
pie(marksss)
pie(x)
pie(rel.freq)
pie(cum.freq)
table(marksss)
cat(marksss)
breaks=seq(9,17,by=1)
marksss
marksss.cut=cut(marksss,breaks)
marksss
marksss.cut
cat(marksss)
range(marksss)
marksss.table=table(marksss.cut)
cbind(marksss.table)
pie(marksss.table)
hist(table(marksss.table))
